# Generated by Django 2.1 on 2018-09-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_salesman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesman',
            name='date_publish',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
