# Generated by Django 2.1 on 2018-09-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180904_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salesman',
        ),
    ]
