# Generated by Django 2.1 on 2018-09-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_delete_salesman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.PositiveSmallIntegerField()),
                ('createData', models.IntegerField()),
                ('date_publish', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
