# Generated by Django 2.1 on 2018-09-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_salesman'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salesman',
        ),
    ]
